<a href="https://colab.research.google.com/github/anhduc02/anhduc02/blob/main/anhduc_py.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [8]:
import numpy as np 
from PIL import Image, ImageOps
from matplotlib import pyplot as plt
np.set_printoptions(suppress=True)
a = np.random.randint(10,size=(3,4))
print(a)

[[9 7 8 9]
 [3 3 5 7]
 [2 9 8 7]]


In [15]:
U, S, V = np.linalg.svd(a)
print(U)
print("-"*100)
print(S)
print("-"*100)
print(V) 

[[ 0.70512877  0.5903522   0.392782  ]
 [ 0.40256218  0.12271665 -0.90712971]
 [ 0.58372691 -0.79776243  0.15112243]]
----------------------------------------------------------------------------------------------------
[23.09535628  5.03101723  2.50866179]
----------------------------------------------------------------------------------------------------
[[ 0.37762134  0.49348146  0.53359889  0.57371631]
 [ 0.81212103 -0.53254569 -0.20785033  0.11684503]
 [ 0.44481632  0.55335745 -0.07351057 -0.70037859]
 [ 0.          0.40824829 -0.81649658  0.40824829]]


In [16]:
U_T = np.transpose(U)
print(U_T)
print(U.dot(U_T))

[[ 0.70512877  0.40256218  0.58372691]
 [ 0.5903522   0.12271665 -0.79776243]
 [ 0.392782   -0.90712971  0.15112243]]
[[ 1.  0.  0.]
 [ 0.  1. -0.]
 [ 0. -0.  1.]]


In [24]:
# Tạo ma trận đường chéo với các phân tử từ S:
M = np.zeros((3,4))
print(M)
for i, x in enumerate(S):
 M[i, i] = x
print(M) 
# Khôi phục lại ma trận A
#B = U@Sigma@V
#print(B)
#print(A-B)


[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]
[[23.09535628  0.          0.          0.        ]
 [ 0.          5.03101723  0.          0.        ]
 [ 0.          0.          2.50866179  0.        ]]


In [23]:
rd = U.dot(Sigma.dot(V))
print(rd)


[[9. 7. 8. 9.]
 [3. 3. 5. 7.]
 [2. 9. 8. 7.]]
